import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {Box, Heading, Text} from "@chakra-ui/layout";
import {Button, FormControl} from "@chakra-ui/react";
import Link from "next/link";
import {Form} from "@chakra-ui/theme/components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fund My food bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as={'h2'} textAlign={'center'} mt={8}>We make it easier to donate equally to your local food banks.
          Support your community with us!  </Heading>
        <Box display={'flex'} justifyContent={'center'} mt={20}>
            <form action="/donation" method={'get'}>
                <FormControl>
                    <Button type={'submit'} bg={'green.500'} color={'#fff'} _hover={{background: 'green'}}>
                        Find your local food banks
                    </Button>
                </FormControl>
            </form>
        </Box>
    </div>
  );
};

export default Home;
